import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";
import { API_URL } from "../config";
import { selectToken } from "../slices/auth.slice";

export const productAPI = createApi({
  reducerPath: "productManagement",
  tagTypes: ["ProductList"],
  baseQuery: fetchBaseQuery({
    baseUrl: API_URL,
    prepareHeaders: (headers, { getState }) => {
      const token = selectToken(getState()); // Retrieve token from Redux state using selectToken selector
      if (token) {
        headers.append("Authorization", `Bearer ${token}`);
      }
      headers.append("Content-Type", "application/json");
      return headers;
    },
  }), endpoints: (builder) => ({

    getProducts: builder.query({
      query: () => `Product/GetAllProducts`,
      providesTags: (result, _error, _arg) =>
        result
          ? [
            ...result.map(({ id }) => ({ type: "productManagement", id })),
            { type: "ProductList", id: "LIST" },
          ]
          : [{ type: "ProductList", id: "LIST" }],
    }),
    getProductsById: builder.query({
      query: (id) => `Product/ViewProductDetail?productId=${id}`,
      providesTags: (result, error, id) => [{ type: "ProductList", id }],
    }),

    addProduct: builder.mutation({
      query: (body) => {
        return {
          method: "POST",
          url: `Product/AddNewProduct`,
          body,
        };
      },
      invalidatesTags: [{ type: "ProductList", id: "LIST" }],
    }),
    editProduct: builder.mutation({
      query: (payload) => {
        console.log(payload);
        return {
          method: "PUT",
          url: `Product/UpdateProduct?productId=${payload.productId}`,
          body: payload,
        };
      },
      invalidatesTags: (res, err, arg) => [{ type: "ProductList", id: arg.id }],
    }),
    deleteProduct: builder.mutation({
      query: (id) => {
        return {
          method: "DELETE",
          url: `Product/DeleteProduct?id=${id}`,
        };
      },
      invalidatesTags: (_res, _err, _arg) => [
        { type: "ProductList", id: "LIST" },
      ],
    }),
    updateStatusProduct: builder.mutation({
      query: (id) => {
        return {
          method: "PUT",
          url: `Product/UpdateStatus?uid=${id}`,
        };
      },
      invalidatesTags: (_res, _err, _arg) => [
        { type: "ProductList", id: "LIST" },
      ],
    }),
  }),
});

// Export hooks for usage in functional components, which are
// auto-generated based on the defined endpoints
// Hooks are auto-generated by RTK-Query
export const {
  useGetProductsQuery,
  useGetProductsByIdQuery,
  useAddProductMutation,
  useEditProductMutation,
  useDeleteProductMutation,
  useUpdateStatusProductMutation

} = productAPI;
